### ISSUE TITLE
Reevaluate how built-in rules are tested

### ISSUE THREAD

**Issue by VeraBE** [Azure/template-analyzer#175]
Considering that adding properties to existing resources in a test template would change the line numbers for other rule tests that rely on them, and that sometimes even using the same template file would imply adding many more cases than needed in the test file of the new rule, or editing all the previous resources to pass the rule (shifting line numbers of other rules too): we might want to reevaluate how built-in rules are tested

We might also want to improve/standardize how passing test cases are documented: in the test file? In the test template inside each resource? As a comment? As a JSON property?

The discussion came up in PR #171

**Comment by VeraBE** [comment]
In the first option, you mean that each template is paired with one test config, right? Because right now we have each test config paired with one or more test templates. If that's the case then I vote in favor of the first option, considering how reusing resources by adding properties to them still would shift line numbers

The idea of adding passing assertions sounds very good too

**Comment by JohnathonMohr** [comment]
Example directory/file structure of the first option:

**Analyzer.Core.BuiltInRuleTests**
&nbsp;   |-- **TestDirectory1**
&nbsp;   |------ *testConfig.json*
&nbsp;   |------ *testTemplate1.badtemplate*
&nbsp;   |------ *testTemplate2.badtemplate*
&nbsp;   |-- **TestDirectory2**
&nbsp;   |------ *testConfig.json*
&nbsp;   |------ *testTemplate1.badtemplate*
&nbsp;   |-- **TestDirectory3**
&nbsp;   |------ *testConfig.json*
&nbsp;   |------ *testTemplate1.badtemplate*
&nbsp;   |------ *testTemplate2.badtemplate*
&nbsp;   |------ *testTemplate3.badtemplate*

The test configuration in each directory would be similar to (possibly the same as) how it's defined today, but only templates that are in the same directory can be specified.  The reorganization of templates helps to make it easier to understand the context of a test config, and enforcing templates to live in the same directory as the config helps keep that organization.

This doesn't change much of the *behavior* from what it is currently, but helps cut down on confusion.  This approach can be combined with option 2, or instead of option 2 (or take option 2 and not option 1).

The final suggestion of making passes explicit can of course be in addition to any combination of options 1 & 2.
