### ISSUE TITLE
Add SARIF output support

### ISSUE THREAD

**Issue by yongyan-gh** [Azure/template-analyzer#190]
Hello team,

CC @michaelcfanning / @eddynaka / @shaopeng-gh, owners of [SARIF-SDK](https://github.com/Microsoft/sarif-sdk)
As discussed in another email thread, we are glad to provide helps to implement SARIF output for ARM Template Best Practice Analyzer.

What we plan to do:
- Look into the current report format of BPA
- Map BPA results to SARIF models
- Once reviewed/confirmed, implement the SARIF output for the tool

Please let us know if any question.

Thanks,
Yong

**Comment by yane3628** [comment]
An example of nested IEvaluations would be if there is a rule that has an AND operator and multiple tokens in the operator fail. When we print results in the CLI, we flatten the failed evaluations, so it should be good to work the same way in the SARIF.

**Comment by yongyan-gh** [comment]
@yane3628 / @yane3628 need clarification regarding the results set. Let me use rule TA-000028 as an example:
The rule definition:
https://github.com/Azure/template-analyzer/blob/a17ed880b197d6117dd7ef812303691509a21f31/src/Analyzer.Core/Rules/BuiltInRules.json#L724-L745
My understand is if the target resource (type is Microsoft.Sql/servers/auditingSettings) has properties satisfy any of below 3 conditions then its a pass, otherwise its a failed result.
1. isAzureMonitorTargetEnabled = true AND storageEndpoint has no value
2. OR retentionDays = 0 (unlimited retention)
3. OR retentionDays >= 90

The test template has 1 resource doesn't match above condition so analyzer reports 1 failed result.
https://github.com/Azure/template-analyzer/blob/a17ed880b197d6117dd7ef812303691509a21f31/src/Analyzer.Core.BuiltInRuleTests/TestTemplates/SQLServerAuditingSettings.badtemplate#L140-L151

The evaluation has multiple failed sub-evaluation and results, so the console output prints multiple lines for this evaluation they all pointed to same resource instance.
```
        TA-000028: SQL servers with auditing to storage account destination should be configured with 90 days retention or higher
                More information: https://github.com/Azure/template-analyzer/blob/main/docs/built-in-bpa-rules.md/#ta-000028-sql-servers-with-auditing-to-storage-account-destination-should-be-configured-with-90-days-retention-or-higher
                Result: Failed
                Line: 146
                Line: 147
                Line: 148
                Line: 148
```

In SARIF output, each result should present 1 distinct occurrence of the issue detected by analysis tool. So I would like to produce 1 result for this evaluation, and add multiple locations to the result according to SARIF spec [3.27.12](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317650)

Please let me know what you think?

**Comment by JohnathonMohr** [comment]
@yongyan-gh your proposal (a single result for the evaluation, having a location for each line number reported) makes sense to me.  However, looking at the spec you linked to, that does appear to go against this guidance:
> *The locations array SHALL NOT contain more than one element unless the condition indicated by the result, if any, can only be corrected by making a change at every location specified in the array*

In this example rule, correcting *any* of the lines would alleviate the violation, so not all are required.  Unfortunately, having multiple results (one for each discovered location) also seems to go against the guidance, since they are not necessarily distinct from one another.

Since multiple locations in a single result seems to be the most logical (at least to me), that would be my vote.

**Comment by yane3628** [comment]
The expectation for anyOf and allOf would be slightly different though. If there are multiple evaluations in an allOf, it would be expected for all of the violations to be remediated. Would this distinction cause any issues with the proposal to have multiple locations for a given result?

**Comment by yongyan-gh** [comment]
Trying to construct a SARIF result for each distinct violation detected by analyzer.
e.g. below rule has 4 results but all point to same section in json template. 
```
        TA-000028: SQL servers with auditing to storage account destination should be configured with 90 days retention or higher
                More information: https://github.com/Azure/template-analyzer/blob/main/docs/built-in-bpa-rules.md/#ta-000028-sql-servers-with-auditing-to-storage-account-destination-should-be-configured-with-90-days-retention-or-higher
                Result: Failed
                Line: 146
                Line: 147
                Line: 148
                Line: 148
```
I d like to create a SARIF result at the evaluation level which includes these 4 results, means need to group results at certain evaluation level instead of flatted results.

But I found different rules group results at different level. E.g. TA-000022 results should be grouped at root evaluation level (each result under root evaluation presents for 1 violation), TA-000028 results should be grouped at second evaluation level (all results under 2nd level evaluation present for 1 violation).

How should I handle the difference among rules and identify proper violations? 

Thanks

**Comment by JohnathonMohr** [comment]
This is an interesting problem @yongyan-gh, thanks for bringing it up.

At this time we don't have a clear mechanism to identify proper grouping of violations, so that will need to be improved later.  For now we should either:
1. Flatten all the `Result`s into distinct SARIF results
2. Map each `Evaluation` to a SARIF result and include each sub-violation (`Result`) as a location in the SARIF result

Option 1 could result in some noise (since fixing one violation could potentially fix others as well), while option 2 would mean there would only ever be at most 1 result per file for each rule (so any file with violations would never have the same rule violated more than once - each violation of the rule would be a new location in the single SARIF result for the rule).

For now, I think either option will do, until we can improve it later.

**Comment by yongyan-gh** [comment]
Thanks for confirming, I prefer first option for now, so the results will be align with console output, and users will be easier to figure out where the issue locates in template.

**Comment by michaelcfanning** [comment]
Hello! I'm spinning up here but some thoughts from a tool user standpoint. The SARIF spec advises that tools bundles together data that comprises a single user action/evaluation, into a single result. This guidance is designed to maximize review/suppression: if it only makes sense to suppress/accept a subset of analysis results, then it makes sense to group it into on result. 

If there are discrete analyses/decision-making, then you break these apart into unique results. 

@yongyan-gh, can you send me the scan target file offline for your example above? I need to understand the quality issues we're identifying here and correlate them to the underlying scan data to actually help out.
