### ISSUE TITLE
[BUG] Array of objects is not being evaluated correctly

### ISSUE THREAD

**Issue by lucas-lelis** [Azure/template-analyzer#246]
### Describe the bug

When trying to use a wildcard to evaluate an array of objects to validate if an object key exists in each array entry the rules are not evaluated properly:
```
{
    "name": "resourceName",
    "type": "Microsoft.Resources/deployments",
    "apiVersion": "2021-04-01",
    "resourceGroup": "resourceGroup",
    "properties": {
        "mode": "Incremental",
        "templateLink": {
            "id": "<Template-Link>"
        },
        "parameters": {
            "secretsObject": {
                "value": {
                    "secrets": [
                        {
                            "secretValue": "secret-value-1"
                        },
                        {
                            "secretValue": "secret-value-2"
                        }
                    ]
                }
            }
        }
    }
}
```

Rule:
```
"evaluation": {
  "resourceType": "Microsoft.Resources/deployments",
  "allOf": [
    {
      "path": "properties.parameters.secretsObject.value.secrets[*].secretName",
      "exists": true
    }
  ]
}
```
    

### Expected behavior

It should fail without the need to add a specific evaluation to each array entry:

```
"path": "properties.parameters.secretsObject.value.secrets[0].secretName"
"path": "properties.parameters.secretsObject.value.secrets[1].secretName"
```

### Reproduction Steps

Run the tool against a template like the example above.

**Comment by JohnathonMohr** [comment]
Hi @lucas-lelis, thanks for the feedback.

Since wildcards are evaluated based on whether or not the full path resolves to an existing property, I believe the issue here is that the rule isn't returning anything to evaluate since the property in question doesn't exist, so it's skipped.  This is somewhat mentioned in the [rule authoring guide](https://github.com/Azure/template-analyzer/blob/development/docs/authoring-json-rules.md#wildcard-behavior), but is not very clear on what's happening.
> "When a wildcard is used, zero or more paths in the template will be found that match `path`. If zero paths are found, the operator in the `Evaluation` is skipped, as there is nothing to evaluate"

Can you try making a small modification to your rule and let us know if this works for you?
```js
"evaluation": {
  "resourceType": "Microsoft.Resources/deployments",
  "allOf": [
    {
      "path": "properties.parameters.secretsObject.value.secrets[*]",
      "allOf": [
        {
          "path" : "secretName",
          "exists": true
        }
      ]
    }
  ]
}
```
The additional operator used for evaluating the remaining path after the wildcard isn't very intuitive, so I've created #247 to help with this.

**Comment by lucas-lelis** [comment]
Thx for the feedback @JohnathonMohr !
It did work as expected with those changes.
